/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_littlebox_misc_pinul_PiNul */

#ifndef _Included_ca_littlebox_misc_pinul_PiNul
#define _Included_ca_littlebox_misc_pinul_PiNul
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_littlebox_misc_pinul_PiNul
 * Method:    pi
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ca_littlebox_misc_pinul_PiNul_pi
  (JNIEnv *, jobject, jint);

/*
 * Class:     ca_littlebox_misc_pinul_PiNul
 * Method:    nul
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_littlebox_misc_pinul_PiNul_nul
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
